/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BreadCumbComponent: typeof import('./src/components/BreadCumbComponent.vue')['default']
    ButtonComponent: typeof import('./src/components/ButtonComponent.vue')['default']
    CadastroForm: typeof import('./src/components/CadastroForm.vue')['default']
    CardComponent: typeof import('./src/components/CardComponent.vue')['default']
    CarrosselComponent: typeof import('./src/components/CarrosselComponent.vue')['default']
    CompactNavbarComponent: typeof import('./src/components/CompactNavbarComponent.vue')['default']
    FieldComponent: typeof import('./src/components/FieldComponent.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoadComponent: typeof import('./src/components/LoadComponent.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    MenuComponent: typeof import('./src/components/MenuComponent.vue')['default']
    NavbarComponent: typeof import('./src/components/NavbarComponent.vue')['default']
    RadioButtonComponent: typeof import('./src/components/RadioButtonComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextComponent: typeof import('./src/components/TextComponent.vue')['default']
  }
}
